# used by docker-run.sh

version: "3.7"
services:
  sunspot:
    hostname: sunspot
    build:
      context: docker/sunspot/.
      dockerfile: Dockerfile
    ports:
      - "8983:8983"
  minio:
    image: minio/minio
    environment:
      MINIO_ROOT_USER: MinioUser
      MINIO_ROOT_PASSWORD: OpenSesame
    hostname: minio
    command: server ~/storage/minio --console-address ":9001"
    ports:
      - "9000:9000"
      - "9001:9001"

  sqs-mock:
    build:
      context: docker/sqs-mock/.
      dockerfile: Dockerfile
    hostname: sqs-mock
    ports:
      - "9324:9324"
  postgres:
    image: postgres:12-alpine
    environment:
      POSTGRES_DB: medusa
      POSTGRES_USER: root
      POSTGRES_PASSWORD: medusa
    hostname: postgres
  rabbitmq:
    image: rabbitmq
    hostname: rabbitmq
    ports:
      - "5672:5672"
  memcached:
    image: memcached
    hostname: memcached
    ports:
      - '11211:11211'