services:
  medusa-test:
    build:
      context: .
      dockerfile: docker/medusa/Dockerfile-test
    depends_on:
      - postgres
      - rabbitmq
      - memcached
      - sunspot
      - sqs-mock
      - minio
    ports:
      - "3001:3000"
    volumes:
      - .:/app
    environment:
      RAILS_ENV: test
      POSTGRES_DB: medusa_test
      POSTGRES_USER: root
      POSTGRES_PASSWORD: medusa
      POSTGRES_HOST: postgres
      DATABASE_URL: postgres://root:medusa@postgres:5432/medusa_test
      MINIO_ROOT_USER: MinioUser
      MINIO_ROOT_PASSWORD: OpenSesame
    command: >
      bash -c 'rm -f /app/tmp/pids/server.pid && \
        /usr/local/bin/docker-entrypoint-test bundle exec rspec'

  postgres:
    image: postgres:12-alpine
    environment:
      POSTGRES_DB: medusa_test
      POSTGRES_USER: root
      POSTGRES_PASSWORD: medusa
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: always
    ports:
      - "5432:5432"

  rabbitmq:
    image: rabbitmq
    ports:
      - "5672:5672"
    restart: always

  memcached:
    image: memcached
    ports:
      - "11211:11211"
    restart: always

  sunspot:
    hostname: sunspot
    build:
      context: docker/sunspot/.
    ports:
      - "8983:8983"
    restart: always

  sqs-mock:
    build:
      context: docker/sqs-mock/.
      dockerfile: Dockerfile
    ports:
      - "9324:9324"
    restart: always

  minio:
    image: minio/minio
    environment:
      MINIO_ROOT_USER: MinioUser
      MINIO_ROOT_PASSWORD: OpenSesame
    command: server /data --console-address ":9001"
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - minio_data:/data
    restart: always

volumes:
  postgres_data:
  minio_data:
