version: "3.7"

services:
  medusa-test:
    build:
      context: .
      dockerfile: docker/medusa/Dockerfile-test
    environment:
      RAILS_ENV: test
      POSTGRES_DB: medusa_test
      POSTGRES_USER: root
      POSTGRES_PASSWORD: medusa
      POSTGRES_HOST: postgres
    volumes:
      - .:/app
    command: >
      /usr/local/bin/docker-entrypoint-test bundle exec rspec

  postgres:
    image: postgres:12-alpine
    environment:
      POSTGRES_DB: medusa_test
      POSTGRES_USER: root
      POSTGRES_PASSWORD: medusa
    ports:
      - "5432:5432"
    restart: always

  rabbitmq:
    image: rabbitmq
    ports:
      - "5672:5672"
    restart: always

  memcached:
    image: memcached
    ports:
      - "11211:11211"
    restart: always

  sunspot:
    hostname: sunspot
    build:
      context: docker/sunspot/.
    ports:
      - "8983:8983"
    restart: always

  minio:
    image: minio/minio
    environment:
      MINIO_ROOT_USER: minio_user
      MINIO_ROOT_PASSWORD: minio_password
    command: server /data --console-address ":9001"
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - minio_data:/data
    restart: always

volumes:
  postgres_data:
  minio_data:
