development:
  adapter: async

test:
  adapter: async

production:
  adapter: redis
  url: redis://localhost:6379/1
  channel_prefix: medusa_collection_registry_production

demo:
  adapter: redis
  url: redis://localhost:6379/1
  channel_prefix: medusa_collection_registry_production