name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - '**'

jobs:
  rspec-tests:
    name: Run RSpec Tests in Docker
    runs-on: ubuntu-latest
    env:
      RAILS_ENV: test
      POSTGRES_DB: medusa_test
      POSTGRES_USER: root
      POSTGRES_PASSWORD: medusa
      POSTGRES_HOST: postgres

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3

      - name: Set up and Run Tests
        run: |
          docker compose -f docker-compose.test.yml up --build --exit-code-from medusa-test --abort-on-container-exit

      - name: Clean up
        if: always()
        run: |
          docker compose -f docker-compose.test.yml down --volumes --remove-orphans
